security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/*
            provider: users
            entry_point: form_login
            form_login:
                login_path: auth_login
                check_path: auth_login_check
                default_target_path: cabinet_home
                username_parameter: login
                password_parameter: password
                use_referer: true
            logout:
                path: auth_logout
                target: home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage/admin, roles: ROLE_ADMIN }
        - { path: ^/manage, roles: ROLE_USER }
